/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
declare const awsmobile: Record<string, any>
export default awsmobile;
// const awsmobile = {
//     "aws_project_region": "eu-north-1",
//     "aws_cognito_identity_pool_id": "eu-north-1:30ef9beb-33eb-4f81-9e22-2f675ec22893",
//     "aws_cognito_region": "eu-north-1",
//     "aws_user_pools_id": "eu-north-1_eSyysenVp",
//     "aws_user_pools_web_client_id": "6ld7ar4s5tnoligclk4v6el105",
//     "oauth": {},
//     "aws_cognito_username_attributes": [],
//     "aws_cognito_social_providers": [],
//     "aws_cognito_signup_attributes": [
//         "EMAIL"
//     ],
//     "aws_cognito_mfa_configuration": "OFF",
//     "aws_cognito_mfa_types": [
//         "SMS"
//     ],
//     "aws_cognito_password_protection_settings": {
//         "passwordPolicyMinLength": 8,
//         "passwordPolicyCharacters": []
//     },
//     "aws_cognito_verification_mechanisms": [
//         "EMAIL"
//     ],
//     "aws_appsync_graphqlEndpoint": "https://ayvehcptxbhadea3ffbjso7j3i.appsync-api.eu-north-1.amazonaws.com/graphql",
//     "aws_appsync_region": "eu-north-1",
//     "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
//     "aws_appsync_apiKey": "da2-gexzgoxhtzhkfojswkjpnduhyy",
//     "aws_content_delivery_bucket": "wordgame-20250114144403-hostingbucket-dev",
//     "aws_content_delivery_bucket_region": "eu-north-1",
//     "aws_content_delivery_url": "https://djzuudu9j12zb.cloudfront.net"
// };

export default awsmobile;
